name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: toolmantim/release-drafter@v5.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
